CREATE TABLE oneMin (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Distance INT NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE fourMin (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Distance INT NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));

CREATE TABLE thirtyMin (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Distance INT NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE sixtyMin (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Distance INT NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));

CREATE TABLE oneHun (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE fiveHun (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE oneThouK (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE twoThouK (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE fiveThouK (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE sixThouK (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE tenThouK (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE halfMarathon (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Time VARCHAR NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));
	
CREATE TABLE marathon (
	Name VARCHAR NOT NULL,
	Age INT NOT NULL,
	Location VARCHAR NULL,
	Country VARCHAR NOT NULL,
	ClubAffiliation VARCHAR NULL,
	Distance INT NOT NULL,
	Verified VARCHAR NOT NULL,
	Season VARCHAR NOT NULL,
	Test VARCHAR NOT NULL,
	Split FLOAT NOT NULL,
	Watts FLOAT NOT NULL,
	TestID VARCHAR NOT NULL,
	PRIMARY KEY (TestID));